### PR TITLE
Modified project structure based on common Maven template.

### PR DESCRIPTION
**Pull request by MilesDowe**
Creating a pull request to suggest this project structure so that files are not in a single directory.

### CODE REVIEW

**Comment by MilesDowe** [comment]
Assigning to Mark since I can only assign to a single person and he created the repo. :)

**Comment by the-brickster** [comment]
Should I merge this pull request?

**Comment by MilesDowe** [comment]
Haha... Sorry, I reassigned to Mark. I wanted everyone to be able to view
it. If people are cool with the project structure, then we can merge it.

Sorry for the surprise assignment. :P

**Comment by the-brickster** [comment]
fine by me

**Comment by the-brickster** [comment]
hey im going to be afk for a while

**Pull request merged**
